[iex]
environment = "sandbox"
version = "stable"
api_key = "" # add your sandbox api key here

[database]
host = "localhost"
username = "username"
password = "password"
port = 5432
name = "stockreader_db_test"
